### ISSUE TITLE
SPARQL container

### ISSUE THREAD

**Issue by salgo60** [perrohdin/Bildhistoria-Masterdata-och-Wikidata#10]
<img width="287" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/f545fb5d-2666-412d-bed3-e9887cb5f97f">

<img width="200" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/011201f0-0f3c-4a9a-8044-1b1411aaf7f9">

### Exempel där SPA är inblandade
* [Gravplatser](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/155)
* [Inkomst](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/103)
* [Dödsorsak](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/128)
* [Bouppteckning](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/168)
* [Provenance](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/167)
* [Dödsplats](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/159)
* [Bostad](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/122)
* Koppling bilder [wikicommons och wikidata objekt](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/72)
* övningar md boken [Tvåkammar-riksdagen 1867-1970 som finns i SPA uppdelad](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/38)

**Comment by salgo60** [comment]
* [Sparql examples](https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries/examples)
* [A gentle introduction to the Wikidata Query Service](https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/A_gentle_introduction_to_the_Wikidata_Query_Service)
* [Request a query](https://www.wikidata.org/wiki/Wikidata:Request_a_query)
* [svWikipedia Wikidata frågor](https://sv.m.wikipedia.org/wiki/Wikipedia:Wikidatafr%C3%A5gor)

**Comment by perrohdin** [comment]
Magnus, tack för att du vill hjälpa oss. Jag skulle vilja ha hjälp med följande 2 saker


- [ ] UPPGIFT 1: Förra året fick vi från Alicia en lista på svenska och historiska skolor. Dock glömde vi att inkludera platsen i den SPARQLen. Dock har vi ju Q-koder på alla skolor. Jag skulle vilja kunna skicka in en lista på Q-nummer (via CSV?) (tex http://www.wikidata.org/entity/Q89904128  och http://www.wikidata.org/entity/Q90132258). För var och en av dessa Q-nummer skulle jag vilja få tillbaka följande kolumner:

- Q-nummer på skolan (dvs det jag skickat in)
- Namnet på skolan
- Platsens namn - de flesta skolor har nog kommun-namn [located in the administrative territorial entity], men det kan kanske även förekomma städer eller liknande.
- Platsens Q nummer
- Platsens Wikipedia-sida Svenska (om sådan finns)
- Platsens Wikipedia-sida Engelska (om sådan finns)


![bild](https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/77397276/518f50e9-05bb-4b2e-8222-b84dce412559)


----------------

UPPGIFT 2: WIKI-KOPPLING TILL BILDHISTORIAS ORGANISATIONER. Jag har en lista på ca 15 000 aktiva och historiska Företag, Idrottföreningar, Scoutkårer, Myndigheter, Frikyrkor, Fackföreningar. Listan består av namnet i fritext och i vissa fall året när den bildades och upplöstes. Majoriteten består av företagen i RAs lista på aktiebolag 1901-1935 (https://riksarkivet.se/psidata/aktiebolag). Jag skulle vilja skicka in en lista med följande kolumner:

- Bildhistorias Organisations-GUID (finns på alla poster)
- Organisationens namn (fritext) (finns på alla poster)
- Organisationens grundades-datum (tex 1945 eller 1945-06-23) (finns på vissa poster)
- Organisationens upplöstes-datum (tex 1945 eller 1945-06-23) (finns på vissa poster)
- Bildhistorias organisationstyp (tex Företag, Offentlig Förvaltning, Idrottsförening, Fackförening) (finns på alla poster)
- Plats för verksamhet i fritext (finns på vissa poster)

Vi kan använda oss av följande lista: https://portrattarkiv.sharepoint.com/:x:/s/Bildhistoriaarbetsfiler/ERCZ7YxT4TxMomQgzHnN_scBWFAnTEFPyL8KhPB46HBu8g?e=a1Uv4z 

Baserat på ovanstående skulle jag vilja få reda på om organisationen finns i Wikidata eller Wikipedia, enligt följande kolumner: 

- Bildhistorias Organisations-GUID (dvs det som skickades in)
- Organisationens namn (fritext) (dvs det som skickades in)
- Wikidata Q-nummer (om den hittats)
- Organisationens namn i Wikidata (om den hittats)
- Wikpedia SE sida (om sådan finns)
- Wikipedia EN sida (om sådan finns)

**Comment by salgo60** [comment]
@perrohdin känns bäst om vi pratar. Detta är inte SparQL funktioner du vill ha, vilka programmerings kunskaper har ni?

* [ ] **UPPGIFT 1 Önska plats för skola**
** plats är lite diffust det du ritar i bilden  [Q89904128](https://www.wikidata.org/wiki/Q89904128) är egenskapen [P131](https://www.wikidata.org/wiki/Property:P131) finns säkert andra varianter...
*** skall du ha ut P131 kan du använda [hub.toolforge.org](https://hub.toolforge.org/)
**** --> [hub.toolforge.org/Q89904128?property=P131](https://hub.toolforge.org/Q89904128?property=P131) 
***** skall du till svenska Wikipedia --> [hub.toolforge.org/Q89904128?property=P131&lang=sv](https://hub.toolforge.org/Q89904128?property=P131&lang=sv)
***** skall du ha json så skriver du [&format=json](https://hub.toolforge.org/Q89904128?lang=sv&property=P131&format=json)

<img width="597" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/57d47b63-a090-4d28-9538-3a9d4b0d9eff">

----
**Fråga 1:** Hur ser bildhistorias datamodell ut.... är den dynamisk så ni kan lägga till nya egenskaper/fält

* [ ] **UPPGIFT 2: WIKI-KOPPLING TILL BILDHISTORIAS ORGANISATIONER**
* [ ] Jag skulle vilja skicka in en lista med följande kolumner.....

**SVAR Uppgift 2:** det är bara att ladda upp listan på denna GITHUB Issues

**Det är troligen ett jättejobb**
1. Riksarkivets data är enormt grisigt se min [Riksarkivet skuggbacklog](https://github.com/salgo60/Svenskaforsamlingar/issues/2) och dom saknar egen backlog och rättar sällan det man skickar in
2. För att göra detta som jag kallar [reconciliation](https://openrefine.org/docs/manual/reconciling) använder jag verktyg som [Open Refine](https://www.wikidata.org/wiki/Wikidata:Tools/OpenRefine) och du måste säkert skapa nya Wikidata objekt
3. Finns hos NAD ett nytt GUID som vi har i Wikidata men inte mycket använt i WD och Riksarkivet har som sahr dålig data... finns ett [TORA projekt](https://www.riksarkivet.se/tora) som var bra men tror det dött = WD [Property:P4820](https://www.wikidata.org/wiki/Property:P4820)
   3-1. gamla NAD id [Property:P5324](https://www.wikidata.org/wiki/Property:P5324) - [exempel P5324](https://w.wiki/8XTM)
   3-2. nya NAD id = [Property:P9713](https://www.wikidata.org/wiki/Property:P9713) - [exempel P9713](https://w.wiki/8XTQ)

**Comment by perrohdin** [comment]
Uppgift 1: P131 kommer att vara den vanligaste tror jag så vi kan ju börja med den. Kan du skapa en SPARQL där jag kan skicka upp en lång lista på skolornas Q-nummer?

Uppgift2: Vi skall inte skapa nya Wikidata-objekt. Vi skall bara kartlägga vad som redan finns i Wikidata/Wikipedia med hjälp av organisationsnamnet. 

Vi kan prata under dagen. Kanske bäst vi delar skärm. Kan Google Meets passa? Jag finns tillgänglig.

**Comment by salgo60** [comment]
> Kan du skapa en SPARQL där jag kan skicka upp en lång lista på skolornas Q-nummer?

* [video](https://youtu.be/Uk8fpF9QdqI?si=qcOBp-Re-07b-tWk) 

1) enklare om du loppar runt er lista och använder URL och hämtar json namnet som jag visar ovan då kan ni göra det från alla programmeringsspråk 

* se [Notebook hur ni gör med Python](https://github.com/salgo60/Wikidata_riksdagen-corpus/blob/main/Notebook/H%C3%A4mta%20P131.ipynb)

<img width="1023" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/5a81ce3b-e13a-4165-ac1b-d165d320661b">

2) SPARQL - [kod](https://w.wiki/8XUZ) - [resultat](https://w.wiki/8XUa) se [video](https://youtu.be/Uk8fpF9QdqI?si=qcOBp-Re-07b-tWk)

<img width="1205" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/b7e290f0-1cfa-4665-8339-e4ac1104be8f">

**Comment by salgo60** [comment]
> Vi kan prata under dagen. Kanske bäst vi delar skärm. Kan Google Meets passa? Jag finns tillgänglig.

Jag är borta under dagen annars funkar 0735152802 eller dela skärm på https://meet.jit.si/Wikidata-SV

vill du snacka Wikidata med flera har du [idag 14:00 träff med svenskar](https://sv..wikipedia.org/wiki/Wikipedia:Wikitr%C3%A4ffar) dom kör https://meet.jit.si/Wikidata-SV

det är bara hoppa med ofta är det några entusiastiska Wikidata entusiaster… tyvärr räknas inte Wikimedia Sverige in i den samlingen…

![image](https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/c0a46baf-a38b-4985-bffb-845e1c8bde69)

**Comment by perrohdin** [comment]
Om du är borta idag, vilken tid kan passa imorgon att dela skärm? Jag är tillgänglig hela förmiddagen och på eftermiddagen fram till kl 15.

**Comment by salgo60** [comment]
Jag kan nog när som helst efter 9:00 men prata gärna med andra 14:00 idag och förklara dina tankar idéer kanske kan du få någon att starta med koppla ”samma som” Riksarkivet <-> Wikidata eller om dom lär er använda Open Refine
* snyggast är nog att ni precis som Open Street Map enkelt kopplar ”samma som” Wikidata så har ni detta i ert UI plus att ni har API och tidstämplar 

**TODO**

1) ladda upp den Riksarkiv fil du har så kan vi se om den har NAD identifierare - är bara att bifoga din kommentar

2) testa dom 2 lösningar jag visar ovan om dom funkar så är uppgift 1 löst

**Comment by salgo60** [comment]
Kolla in diskussionen kring [identifierare och tombstone sidor](https://github.com/diggsweden/persistent-identifiers-investigation/issues/13) så ni designar er app på ett bra sätt

**Comment by perrohdin** [comment]
Uppgift1: Ser bra ut! Snabbt jobbat! Jag laddade upp en lista på ca 200 Q-nummer enligt nedanstående bild men fick bara 34 träffar. Vad betyder det? Är det sökningen som fastnar eller visas bara de rader som får en träff?

-----------

![bild](https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/77397276/d814c91e-a998-4deb-80ee-b5eab45e92e1)


-------------

![bild](https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/77397276/d2c03b4e-05c6-4f52-b83a-d1dc9f40c3bc)

**Comment by salgo60** [comment]
@perrohdin 

[Property:P131](https://www.wikidata.org/wiki/Property:P131)  = inom det administrativa området

se även [Property:P3842](https://www.wikidata.org/wiki/Property:P3842) = inom nuvarande administrativt område


* egenskaper WIkidata har på skolor I Sverige där skola anges som [wdt:P31/wdt:P279* wd:Q3914; wdt:P17 wd:Q34.](https://w.wiki/8XyB)

* [SPARQL egenskaper](https://w.wiki/8XnJ)

<img width="1393" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/b1ccc4f7-c628-405f-a7ba-4ada1363d818">

<img width="1393" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/ba14f5f1-6d69-4b9b-b624-95d646921819">

<img width="1393" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/f0281951-14c5-4f0e-b1b3-35abf0670f50">


* [SPARQL skolor som har en koordinat](https://w.wiki/8Xyd) **7678 stycken**
   * [SPARQL skolor med koordinat men utan P131](https://w.wiki/8Xyv) = 92 stycken

<img width="1393" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/988c694f-88e8-4d56-b9c6-391229b3c902">

   * klickar man till höger kan man filtrera på det som finns i P131
   
<img width="1004" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/96719719-ed25-47bb-8554-4ee8c8055df7">

   * klickar man till höger kan man ladda ned detta till en csv fil
   
   <img width="709" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/4d633a80-65eb-499c-9b18-62ed4d179167">   
   
   
**Exempel csv fil** [WD skolor Sverige med P131.csv](https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/files/13698751/WD.skolor.msgerige.med.P131.csv)

den ser ut enl. nedan och där P131 ligger i sista kolumnen som jag kalla layer ([för att kunna visa upp den som filter i kartan](https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/Wikidata_Query_Help/Result_Views/en#Options_2))


```
item,itemLabel,admin,adminLabel,coord,bild,adminP131,layer
http://www.wikidata.org/entity/Q167920,Kungliga Akademien för de fria konsterna,,,Point(18.064419 59.328672),http://commons.wikimedia.org/wiki/Special:FilePath/Konstakademien%20Stockholm.jpg,,
http://www.wikidata.org/entity/Q1064735,Handelshögskolan vid Göteborgs universitet,,,Point(11.961111111 57.697222222),,,
http://www.wikidata.org/entity/Q1541450,Kungliga Musikaliska Akademien,,,Point(18.075819 59.33065),http://commons.wikimedia.org/wiki/Special:FilePath/KMA%20hus.fr%20Nybroviken.jpg,,
http://www.wikidata.org/entity/Q1792159,Kungliga Vitterhetsakademien,,,Point(18.0725 59.341667),http://commons.wikimedia.org/wiki/Special:FilePath/Villagatan%203%2C%20Stockholm.JPG,,

```

* [samma fråga som ovan men med P3842](https://w.wiki/8Xzg) som enligt mig borde ha använts för skolor som upphörde innan 1971
<img width="992" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/f2ab989c-3206-4cf2-a056-14a93c385f2f">
----
 
### Skolenhetskod - SCB länkröta

* Alla skolor i Sverige skall ha en unik kod som [Skolverket](https://www.skolverket.se/skolutveckling/skolenhetsregistret) och [SCB](https://www.scb.se/lamna-uppgifter/undersokningar/Skolenhetsregistret/) skapat
* den finns som [Property:P7894](https://www.wikidata.org/wiki/Property:P7894) i Wikidata men verkar ha **flyttats/tagits bort och ger länkröta**

* [SPARQL](https://w.wiki/8Y43)

<img width="1336" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/f25a5e30-f053-481c-86d4-fdc095531942">

<img width="973" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/0dc8bd77-f66b-4580-ba35-9adf17f7380b">

#### SKALL detta fungera skall man ha

* Persistenta Unika Identifierare PID - se [DIGGs taffliga försök att styra upp detta](https://github.com/diggsweden/persistent-identifiers-investigation)
   * Statsverket sågning av DIGG - [Myndighetsanalys av Myndigheten för digital förvaltning  2023:18](https://www.statskontoret.se/siteassets/rapporter-pdf/2023/2023_18---utskriftsformat.pdf)
* Om en PID tas bort skall det finnas en [tombstone sida](https://github.com/diggsweden/persistent-identifiers-investigation/issues/13)/ versionshantering och gärna [PROV](https://github.com/diggsweden/persistent-identifiers-investigation/issues/13#issuecomment-1806575996) (se [Riksdagens Corpus tankar](https://github.com/welfare-state-analytics/riksdagen-corpus/issues/421) och min [test med WD och SPA porträttböcker som har lite olika tankar om politiska "vildar"](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/139))

**Comment by salgo60** [comment]
### Wikidata cache
det vi gör med Wikipedia och wikicommons är att cacha data som hämtas från Wikidata som sedan kan hämtas igen se video dvs, ändras datat i wikidata så slär det igenom då cachen uppdateras

* [video](https://youtu.be/COaCc8UKg9I)

**Comment by salgo60** [comment]
@perrohdin 

756 matchade

Exempel där kolumn 4:a har wkidata nummer
```
GUID_Bildhistoria,MainName,Lsv,Wikidata,OrganisationType,FoundedDate,DissolvedDate,PlaceOfBusiness1_Name_FullName,PlaceOfBusiness2_Name_FullName,PlaceOfBusiness3_Name_FullName,Source1_Name,SourceId1,SourceText1,SourceId2,SourceText2,SourceId3,SourceText3,WikiData,WikipediaSE,WikipediaEN,DigitaltMuseum,Riksarkivet
f5c2f591-2ab6-4414-9fdf-2fa798af5f5b,Lokala säkerhetsnämnden vid Forsmark,Lokala säkerhetsnämnden vid Forsmark,Q80207112,Offentlig Förvaltning,1981,,"Östhammar, Östhammar, Uppsala län",,,Wikipedia,f5bf0de9-dc69-47d3-82da-0a359e9d7a40,,,,,,,,,,
8187b431-67f7-4f46-b667-e49503441898,Clarion Hotel Grand Östersund,,Q111410023,Företag,1935,,"Östersund, Östersund, Jämtlands län",,,Riksarkivet Aktiebolag 1901-1935,81fc68d8-418f-4206-b132-b7491a0dc1d4,8902,,,,,,,,,
00e21ffc-a853-4fa7-8bef-426115136840,Länsstyrelsen i Jämtlands län,Länsstyrelsen i Jämtlands län,Q28797491,Offentlig Förvaltning,1810,,"Östersund, Östersund, Jämtlands län",,,Wikipedia,f5bf0de9-dc69-47d3-82da-0a359e9d7a40,,,,,,,,,,
482b53dd-1089-412b-acd6-8ababbcd34f4,Myndigheten för tillväxtpolitiska utvärderingar och analyser,Myndigheten för tillväxtpolitiska utvärderingar och analyser,Q10591753,Offentlig Förvaltning,2009,,"Östersund, Östersund, Jämtlands län",,,Wikipedia,f5bf0de9-dc69-47d3-82da-0a359e9d7a40,,,,,,,,,,

```

[ORGANISATIONER-wiki-Dec2023-xlsx.csv](https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/files/13730997/ORGANISATIONER-wiki-Dec2023-xlsx.csv)

**Comment by perrohdin** [comment]
Grymt! Jag hade förväntat mig fler men det här är fantastiskt. Via ChatGPT, lyckades jag sedan köra en query som hittade matchande Wikipedia sidor på svenska och engelska. Tack igen!

**Comment by salgo60** [comment]
Det är mycket "gegga" som scoutkårer och det är lite för lite bra info hos Riksarkivet

1. jag körde Open Refine automatch

<img width="1253" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/b91d7373-ef90-49d0-887c-f477dfa02322">

2. sedan gick igenom 800 stycken för hand och kolla när flera alternativ var föreslagna

3. tar du exempel Torpshamra så finns det massa Torpshamra i Wikidata men ofta är det orter, museer som gar artikel....

<img width="1253" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/a0e38727-95aa-4dba-89a7-5e55f8c848b2">

4. att modulera organisationer över tid dvs. koncern / vilka namn byten som sker och vilka som köps upp kan vara svårt och tror wikipedia folk mer leker med influencers och adel gubbar....

### Lesson learned
att koppla "samma som" är även för enkla saker som personer/bolag kostsamt. DIGG tittar nu lite på detta men jag känner inte att dom tar höjd för att verkligen koppla ihop eftersom mitt förslag att [skapa ett ekosystem avslogs som utanför projektets scope...](https://github.com/diggsweden/persistent-identifiers-investigation/issues/20)

**Comment by salgo60** [comment]
@perrohdin Du visade mig aldrig er datamodell men att ha **organisationsnummer** kan vara en ide även [Riksarkivet NAD](https://sok.riksarkivet.se/nad) har ett agent id i wikidata (är nog mest jag som sätter den)...

* [Property:P6460](https://www.wikidata.org/wiki/Property:P6460) "organisationsnummer (Sverige)" - **219 stycken**
* [Property:P9713](https://www.wikidata.org/wiki/Property:P9713) "Nationell arkivdatabas agent-id "  **endast 3 stycken**

bifogar fil med dessa värden för listan ovan

[ORGANISATIONER-wiki-Dec2023 orgnr NADagent.csv](https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/files/13737808/ORGANISATIONER-wiki-Dec2023.orgnr.NADagent.csv)

exempel

```
GUID_Bildhistoria,MainName,Nationell arkivdatabas agent-id,organisationsnummer (Sverige),Lsv,Wikidata
f5c2f591-2ab6-4414-9fdf-2fa798af5f5b,Lokala säkerhetsnämnden vid Forsmark,,202100-6735,Lokala säkerhetsnämnden vid Forsmark,Q80207112
8187b431-67f7-4f46-b667-e49503441898,Clarion Hotel Grand Östersund,,,,Q111410023
00e21ffc-a853-4fa7-8bef-426115136840,Länsstyrelsen i Jämtlands län,,202100-2452,Länsstyrelsen i Jämtlands län,Q28797491
482b53dd-1089-412b-acd6-8ababbcd34f4,Myndigheten för tillväxtpolitiska utvärderingar och analyser,,202100-6164,Myndigheten för tillväxtpolitiska utvärderingar och analyser,Q10591753

```

<img width="1241" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/d05a95e9-34e7-4045-914c-a312f587562d">

<img width="1241" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/4f218f5a-2d9e-4371-ad3e-dffa586cea21">

**Comment by perrohdin** [comment]
Jag kikar just nu på https://openrefine.org/docs/manual/reconciling - och försöker köra Reconciling på våra Organisationer, Platser, Källor och Personer. Tack för tipset!

**Comment by salgo60** [comment]
@perrohdin skrik till om vi skall dela skärm några minuter det är ett kraftfullt verktyg **men inte helt lätt** jag drar 15:00 på julbord till Sthlm Fisk 

* finns en [server version](https://meta.wikimedia.org/wiki/OpenRefine#Cloud_version_of_OpenRefine_(on_PAWS)_for_Wikimedians) om man inte vill installera den lokalt
* [programminghistorian.org](https://programminghistorian.org/en/lessons/cleaning-data-with-openrefine) har rel. bra kurser se [fler kandidater](https://programminghistorian.org/en/lessons/?search=open+refine)

**Comment by salgo60** [comment]
SPA har en begränsning på att man kan bara hämta **10 000 poster i api.et** men vi har tagit ned det vi kunnat så det finns i en speciell katalog innan wikidata som heter [mix-and-match](https://mix-n-match.toolforge.org/#/catalog/4837)

* [SPA 4827](https://mix-n-match.toolforge.org/#/catalog/4837)
   * [lista med förslag ](https://mix-n-match.toolforge.org/#/list/4837/auto)

<img width="1241" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/ab22442d-75f1-43bf-98a0-e491dfd622ed">

<img width="1241" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/8bc2ee83-ece4-425c-beca-d50e93c6efc4">

* [finns i mobil game variant](https://mix-n-match.toolforge.org/mobile_game.html?catalog=4837)

<img width="1241" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/731b453a-bf2b-4bcb-9842-f277d6e62e47">

<img width="1241" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/395d2f19-e478-43d3-b17c-d89f7d096500">

* [Visual mode](https://mix-n-match.toolforge.org/visual_match.html#catalog=4837&auto_advance=1)

<img width="1398" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/d34e7395-6821-4746-8d56-85da84674654">

<img width="1398" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/273f7ed4-8aa6-4342-ab8f-759d802413d7">

**Comment by salgo60** [comment]
**Ortsnamn Isof**

FYI; @perrohdin 

@dpriskorn frågade -  [ISOF](https://www.isof.se/) om vilka som använ der deras ortsnamns data och fick en maskad lista vilka som frågar.... kanske kan ge dig ledtrådar vilka som har lite action

[ÖD4.pdf](https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/files/13740654/OD4.pdf)

* [fler frågor till isof](https://handlingar.se/body/isof)

**edit** verkar vara bara Dennis... som skriver under uppenbar pseudonym...
